# Generated by Django 4.2.7 on 2023-11-04 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_status', models.CharField(blank=True, choices=[('Shared', 'Shared'), ('Private', 'Private')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Phone : ')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Customer E-mail : ')),
                ('check_in', models.DateField(verbose_name='Check in : ')),
                ('check_out', models.DateField(verbose_name='Check out : ')),
                ('status', models.CharField(blank=True, choices=[('Shared', 'Shared'), ('Private', 'Private')], max_length=50, null=True)),
                ('custumers_numbers', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost ')),
                ('total_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total : ')),
                ('notes', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer Name : ')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Room Number ')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservation',
            },
        ),
    ]
